### ISSUE TITLE
Error when binding with dependency of TCA (Composable Architecture)

### ISSUE THREAD

**Issue by rzolin** [Kolos65/AsyncBinding#1]
Hey, I am trying to build the app using The Composable Architecture (https://www.pointfree.co/collections/composable-architecture) and I setup a dependency for async array which is a part of an actor (`ATLinkedAccounts`) 
```
public var linkedAccounts: AsyncThrowingStream<Array<String>, Error> {
        .init { ATSDK.config.linkedAccounts.accounts }
    }
```

And now trying to link it all together:

```
    @Dependency(\.config) var config

    @AsyncBinding var linkedAccounts: Array<ATUserAccount>

...

            NavigationStack {
               if let account = config.primaryUserAccount {
                    let store = Store(initialState: ATAccountProfileSummaryFeature.State(currentUserAccount: account, linkedAccounts: linkedAccounts)) {
                        ATAccountProfileSummaryFeature()
                    }
                    ATAccountProfileSummaryView(
                        store: store,
                        showingProfile: $showingProfile,
                        showCloseButton: true
                    )
                }
            }
            .bind {
                config.linkedAccounts.assign(to: $linkedAccounts)
            }
   ```
  
And now I am getting the error:
![image](https://github.com/Kolos65/AsyncBinding/assets/316550/029bf8ac-51e2-4da1-a4e3-44fec8031baf)

![image](https://github.com/Kolos65/AsyncBinding/assets/316550/f9ccd90e-204c-4ee1-afc3-a1f6659db6d3)

I know, it's may not be the bug per se, but a compatibility issue. And just wanted to figure out how to solve it. Your AsyncBinding seems to be a neat way to work with async values and I'd like to keep using it. I haven't dug deep into async and Combine, and probably missing something here. And it's very possible it's not your issue at all. Appreciate the work and any help

**Comment by Kolos65** [comment]
Hey @rzolin 🙋‍♂️

Thanks for the issue! 
I added a new [release (0.0.2)](https://github.com/Kolos65/AsyncBinding/releases/tag/0.0.2), can you check with that version?

**Comment by rzolin** [comment]
It looks like it works. At least no error right now, still need to check that my values propagate correctly. And I had to switch to `.branch("main")`, because `.upToNextMajor(from: "0.0.1")` didn't pull the changes

**Comment by rzolin** [comment]
Yes, all works now. Thanks for your help!
